name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write

jobs:
  build:
    strategy:
      matrix:
        compiler:
        # - {
        #     name: "x86_64-8.1.0-release-posix-seh-rt_v6-rev0",
        #     url: "https://github.com/dirkarnez/cpp-tools/raw/main/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z"
        #   }
        # - {
        #     name: "winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1",
        #     url: "https://github.com/brechtsanders/winlibs_mingw/releases/download/11.2.0-12.0.1-9.0.0-r1/winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1.zip"
        #   }
        - {
            name: "msvc2022"
          }

    runs-on: windows-latest
    # env:
    #   tagName: 0c4e4be342208e621fc969e501d44b3b69fb61eb
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'lvgl/lv_port_pc_visual_studio'
          submodules: true
          
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - run: |
          msbuild LVGL.sln /p:configuration=release /t:LvglWindowsSimulator

# D:\a\lvgl-windows-port-prebuilt\lvgl-windows-port-prebuilt\Output\Binaries\Release\x64\LvglWindowsSimulator.exe
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "Output"
          filename: "lv_port_pc_visual_studio-${{ github.ref_name }}-${{ matrix.compiler.name }}.zip"
        
      - name: Release prebuilt
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "Output/lv_port_pc_visual_studio-${{ github.ref_name }}-${{ matrix.compiler.name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
